FinalMeta5/front-end

- hiapp/src/components/CarShareInformationComponent.vue
- hiapp/src/views/AvailableMapView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
- 컴포넌트 구현
- Kakao map API (JS Key) 연결하여 지도 출력
- Kakao map API (REST Key) 연결하여 장소 검색 기능 구현
- 내 위치가 빨간색 원으로 표시
- 장소 검색 후 클릭 시 해당 장소로 지도가 이동하며 파란색 원으로 표시
- 백앤드 및 DB 연결 성공 1 => 지도 위에 이용 가능한 공유 차량 출발 위치가 부르릉 마커로 표시
- 백엔드 및 DB 연결 성공 2 => 부르릉 마커 선택 시 해당 차량 공유에 대한 내용 출력
> Create available careshare list in map

- hiapp/src/components/CarShareInformationComponent.vue
- hiapp/src/views/AvailableMapView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/carshare/participant/availablelist -> dev
- 컴포넌트 구현 
- Kakao Map API (JS Key)  활용하여 지도 출력
- KAkao Map API (REST Key) 활용하여 장소 및 주소 검색 구현
- 현재 내 위치가 빨간색 원으로 표현
- 장소를 검색하면 해당 주소로 지도가 이동하고 파란색 원으로 표현
- 백엔드 및 DB 연결 성공 1 => 이용 가능한 차량이 지도 위에 부르릉 마커로 표현
- 백엔드 및 DB 연결 성공 1 => 부르릉 마커 클릭하면 해당 차량 공유에 대한 정보 출력
> Create: 이용 가능한  공유 차량 리스트 출력

- hiapp/src/components/BannerComponent.vue
- hiapp/src/router/index.js
- hiapp/src/views/AvailableMapView.vue
- hiapp/src/views/HomeView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
- 지도에서 현재 위치로 돌아가는 버튼 추가
- 버튼 클릭 시 현재 나의 위치로 지도 변환
> Feat: 현재 위치로 돌아가는 버튼 추가

- hiapp/src/components/CarShareInformationComponent.vue
-[] 기능 추가
-[] 기능 삭제
-[] 버그 수정
- 컴포넌트 디자인 변경
- 닉네임과 출발지 및 도착지 정보 사이에 직선 추가
> Design: 컴포넌트 디자인 수정

- hiapp/src/components/CarShareInformationComponent.vue
- hiapp/src/views/AvailableMapView.vue
-[] 기능 추가
-[] 기능 삭제
-[] 버그 수정
- 공유 차량 정보 출력 컴포넌트 디자인 수정
- 공유 차량 정보 출력 컴포넌트 디자인 수정
> Design: 공유 차량 정보 출력 컴포넌트 디자인 수정

- hiapp/src/components/CarShareInformationComponent.vue
- hiapp/src/views/AvailableMapView.vue
-[] 기능 추가
-[] 기능 삭제
-[v] 버그 수정
- 주소 검색 컴포넌트 디자인 수정
- 주소 검색 컴포넌트 디자인 수정
> Design: 주소 검색 컴포넌트 디자인 수정

- hiapp/package-lock.json
- hiapp/package.json
- hiapp/src/views/AvailableMapView.vue
-[] 기능 추가
-[] 기능 삭제
-[v] 버그 수정
- 검색 창 버그 수정
- 검색창 초기 렌더링 문구 : 현재 위치의 법정동 주소
- 검색창 포커스 문구 : 장소 또는 주소 검색
- 주소 검색 후 검색창 문구 : 장소명 (주소)
> Fix: 검색창 버그 수정

- hiapp/package-lock.json
- hiapp/package.json
- hiapp/src/assets/style/CarRegistraion.css
- hiapp/src/components/car-share/CarRegiForm.vue
- hiapp/src/router/index.js
- hiapp/src/views/MypageView.vue
- hiapp/src/views/car-share/CarRegistrationView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/car-registration -> dev
- 차량 등록 폼 백 연결 구현 중
- 마이페이지에 등록 폼 이동 버튼 생성 (테스트용)
- 등록 폼 화면에 보이기
> Feat : 차량 등록 폼 구현 중

- hiapp/src/store/auth/auth.js
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/auth -> develop
- 로그인 시 memberId 저장하도록 변경
> 로그인 시 memberId 저장

- hiapp/package-lock.json
- hiapp/package.json
- hiapp/src/assets/style/CarRegistraion.css
- hiapp/src/assets/style/phone-main-view-common.css
- hiapp/src/components/car-share/CarEditForm.vue
- hiapp/src/components/car-share/CarRegiButton.vue
- hiapp/src/components/car-share/CarRegiForm.vue
- hiapp/src/components/car-share/CarSearchButton.vue
- hiapp/src/components/car-share/CarServiceForm.vue
- hiapp/src/components/car-share/CarShareServiceRegiButton.vue
- hiapp/src/main.js
- hiapp/src/router/index.js
- hiapp/src/views/MypageView.vue
- hiapp/src/views/car-share/CarServiceRegiView.vue
- hiapp/src/views/car-share/MyCarSearchView.vue
- hiapp/src/views/car-share/NoCarInfoView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/car-registration -> develop
- 마이페이지 부분에서 테스트 구현 중 : 마이페이지에 차량 등록, 차량 수정 버튼 생성되어 있음
- 모든 기능 = 로그인 된 사용자만 가능함
- 차량 등록 클릭 시 로그인된 사용자는 등록폼으로 이동 가능
- 차량 등록 클릭 시 로그인되지 않은 사용자는 로그인 모달로 이동
- 차량 등록 클릭 시 등록되지 않은 사용자만 등록 가능
- 차량 수정 클릭 시 등록된 차량이 없을 경우 없다는 화면 출력 + 차량 등록 버튼
- 차량 수정 클릭 시 등록된 차량이 있는 경우 본인의 정보가 출력 + 수정 버튼, 삭제 버튼 구현
- 차량 수정 클릭 시 문서 인증된 사용자는 수정 하기 버튼으로, 문서 인증되지 않은 사용자는 재등록하기 버튼으로 활성화
-  또한, 문서 인증자는 수정 폼에 파일 업로드 필드 없음. 미인증자는 보임
> feat : 차량 등록, 조회, 수정, 삭제 backend 연결

- hiapp/package-lock.json
- hiapp/package.json
- hiapp/src/assets/style/CarRegistraion.css
- hiapp/src/assets/style/phone-main-view-common.css
- hiapp/src/components/car-share/CarEditForm.vue
- hiapp/src/components/car-share/CarRegiButton.vue
- hiapp/src/components/car-share/CarRegiForm.vue
- hiapp/src/components/car-share/CarSearchButton.vue
- hiapp/src/components/car-share/CarServiceForm.vue
- hiapp/src/components/car-share/CarShareServiceRegiButton.vue
- hiapp/src/components/check-modal/AlertModal.vue
- hiapp/src/components/error-modal/ErrorModal.vue
- hiapp/src/main.js
- hiapp/src/router/index.js
- hiapp/src/views/MypageView.vue
- hiapp/src/views/car-share/CarServiceRegiView.vue
- hiapp/src/views/car-share/MyCarSearchView.vue
- hiapp/src/views/car-share/NoCarInfoView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/modal-> develop
- components / 에러 모달, 체크 모달 폴더로 생성해둠 -> 나중에 구조 재설정 필요
- 
- 차량 등록시 차량 번호가 같으면 등록할 수 없다는 모달창 안내가 보임
- 차량 등록시 미기입 필드가 있는 경우 작성 안내 모달창이 보임
> Feature : 에러 관련 모달 구현

- hiapp/src/components/taxi-share/KakaoMap.vue
- hiapp/src/components/taxi-share/PlaceSearchModal.vue
- hiapp/src/components/taxi-share/TaxiShareJoinModal.vue
- hiapp/src/components/taxi-share/TaxiShareList.vue
- hiapp/src/components/taxi-share/TaxiShareRegist.vue
- hiapp/src/views/taxi-share/PathView.vue
-[v] 기능 추가
-[v] 버그 수정
feat/taxi-share -> dev
- 택시 공유 리스트 백 연결
- 택시 공유 리스트 프론트 수정
- 택시 공유 신청 백 연결
- 택시 공유 신청 프론트 구현
> Feat/Modify: 택시 공유 리스트 기능

- hiapp/src/components/car-share/CarEditForm.vue
- hiapp/src/components/car-share/CarRegiButton.vue
- hiapp/src/components/car-share/CarRegiForm.vue
- hiapp/src/components/car-share/CarSearchButton.vue
- hiapp/src/components/car-share/CarShareServiceRegiButton.vue
- hiapp/src/components/error-modal/ErrorModal.vue
- hiapp/src/router/index.js
- hiapp/src/views/LoginModalView.vue
- hiapp/src/views/MypageView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feat/login-modal-connection-> develop
- 로그인 상태가 아닐 때 로그인 모달 이동 후 "/"로 라우팅 되는 부분 수정
- 로그인 모달에서 로그인 완료 시 해당 진행 함수 실행 가능하도록 로직 처리
- 다른 페이지로 넘어갈 수 있는 라우팅 로직도 구현
> Feat : 로그인 모달 창 home 고정 라우팅 로직 변경

- hiapp/src/components/car-share/CarEditForm.vue
- hiapp/src/components/car-share/CarRegiButton.vue
- hiapp/src/components/car-share/CarRegiForm.vue
- hiapp/src/components/car-share/CarSearchButton.vue
- hiapp/src/components/car-share/CarShareServiceRegiButton.vue
- hiapp/src/components/error-modal/ErrorModal.vue
- hiapp/src/router/index.js
- hiapp/src/views/MypageView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/car-registration -> dev
- 차량 등록 버튼 클릭 시 등록된 차량이 있으면 에러 모달창 나옴
- 차량 조회 버튼 클릭 시 등록 차량 없으면 등록하는 페이지로 이동
- 미인증 사용자는 수정할 때 범죄 조회 동의 파일을 올릴 수 있도록 수정 가능 + 재등록 버튼으로 보임
- 인증 사용자 수정할 때 범죄 조회 동의 파일 필드 보이지 않음
- 에러 모달이 잘 떠야 합니다.
> Feat : 차량 등록 crud 관련 버튼 수정 + 인증된 사용자 판단 백 로직 연결

- hiapp/src/components/car-share/CarEditForm.vue
- hiapp/src/components/car-share/CarRegiButton.vue
- hiapp/src/components/car-share/CarRegiForm.vue
- hiapp/src/components/car-share/CarSearchButton.vue
- hiapp/src/components/car-share/CarShareServiceRegiButton.vue
- hiapp/src/components/commons/TopNavComponent.vue
- hiapp/src/components/error-modal/ErrorModal.vue
- hiapp/src/router/index.js
- hiapp/src/views/LoginModalView.vue
- hiapp/src/views/MypageView.vue
-[v] 기능 추가
-[] 기능 삭제
-[v] 버그 수정
feat/top-nav/common-btn -> develop
- 뒤로가기 공통 버튼으로 구현 : 어디서든 그 전 페이지로 돌아갈 수 있어야 함
> Feat : TopNav 뒤로가기 버튼 추가

- hiapp/src/components/car-share/CarEditForm.vue
- hiapp/src/components/car-share/CarRegiForm.vue
- hiapp/src/components/check-modal/AlertModal.vue
- hiapp/src/router/index.js
- hiapp/src/views/car-share/CarShareServiceRegiFirstView.vue
- hiapp/src/views/car-share/CarShareServiceRegiSecondView.vue
- hiapp/src/views/car-share/test.vue
-[v] 기능 추가
-[] 기능 삭제
-[v] 버그 수정
feature/car service registration/seconde page -> dev
- index.js 경로 주석 해제
- 구현 중입니다 
- 첫 페이지에서 주소를 보내면 두번째 페이지에서 받아 처리됩니다.
> Feature : 차량 공유 서비스 등록 2페이지 구현 중

- hiapp/src/assets/style/CarRegistraion.css
- hiapp/src/components/car-share/CarRegiForm.vue
- hiapp/src/views/LoginModalView.vue
- hiapp/src/views/car-share/CarRegistrationView.vue
- hiapp/src/views/car-share/CarShareServiceRegiFirstView.vue
- hiapp/src/views/car-share/CarShareServiceRegiSecondView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/car-share-service/register-seconde-view -> develop
- 로그인 완료되면 바로 알림 표시 떠야 함
- 차량 서비스 등록 페이지에서 입력 값 확인 가능
- 차량 서비스 등록 시 각 필드 값 미입력 시 alert로 표시됨.
- 현재 시점으로 부터 과거의 시간 등록 시 등록 자체가 안됨.
- 최종 입력 확인 후 확정 등록 하면 백으로 데이터 잘 넘어감.
> Feature : 차량 등록 2번째 페이지 / 로그인 후 새로고침(알림 바로 확인 가능)

- hiapp/src/components/taxi-share/TaxiShareJoinModal.vue
- hiapp/src/components/taxi-share/TaxiShareList.vue
-[v] 기능 수정
feat/taxi-share -> develop
- 택시 참여 모달 프론트 수정
- 택시 공유 리스트 프론트 수정
> Modify: 택시 참여 모달,리스트 수정

- hiapp/src/App.vue
- hiapp/src/assets/style/top-bottom-nav-mobile.css
- hiapp/src/components/car-share/MyCarShareSearchButton.vue
- hiapp/src/components/car-share/MyCarShareServiceListForm.vue
- hiapp/src/components/commons/BottomNavComponent.vue
- hiapp/src/components/commons/HeaderComponent.vue
- hiapp/src/components/commons/TopNavComponent.vue
- hiapp/src/router/index.js
- hiapp/src/views/MypageView.vue
- hiapp/src/views/car-share/CarShareServiceRegiSecondView.vue
- hiapp/src/views/car-share/MyCarShareServiceView.vue
- hiapp/src/views/car-share/NoCarShareServiceView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/my-car-share-service-list -> develop
- 차량 공유 서비스 등록
- 내 차량 공유 서비스 리스트 조회
- 차량 공유 서비스 등록 가능 -> 로그인되고 차량이 있고 인증을 받은 사람만 등록 가능
- 차량 공유 서비스 등록 -> 공유 서비스 등록 시 입력 값 미기재일 경우 다음 단계로 넘어가지 못함
- 차량 공유 서비스 -> (요일 x, 날짜만 일단 가능)
- 내 차량 공유 서비스 리스트 조회 가능
- 리스트가 없는 경우 :  등록한 서비스가 없다는 화면으로 넘어가며 뒤로가기 버튼 클릭 시 마이페이지로 이동함
> Feature : 차량 공유 서비스 등록, 내 차량 공유 서비스 조회 가능

- hiapp/src/App.vue
- hiapp/src/assets/style/top-bottom-nav-mobile.css
- hiapp/src/components/commons/BottomNavComponent.vue
- hiapp/src/components/commons/HeaderComponent.vue
- hiapp/src/components/commons/TopNavComponent.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/layouts -> develop
- 헤더 로고 색상 파랑으로 변경
- top nav 부분 로그인되면 회원가입 아이콘 사라짐
- 뒤로가기 버튼 통일화
- 하단 내비 부분 이미지 경로 통일화
- 전체적으로 하얀 바탕으로 구현되었습니다.
> Feat : 레이아웃 재구성

- hiapp/src/components/statistics/AgeGroupRatioComponent.vue
- hiapp/src/components/statistics/GenderRatioComponent.vue
- hiapp/src/components/statistics/MemberRate.vue
- hiapp/src/components/statistics/MonthlyNewMemberComponent.vue
- hiapp/src/router/index.js
- hiapp/src/views/admin/AdminCarShareView.vue
- hiapp/src/views/admin/AdminHomeView.vue
- hiapp/src/views/admin/AdminMembersView.vue
- hiapp/src/views/admin/AdminPaymentView.vue
- hiapp/src/views/admin/AdminRegistrationView.vue
- hiapp/src/views/admin/AdminReportsView.vue
- hiapp/src/views/admin/AdminServicesView.vue
- hiapp/src/views/admin/AdminTaxiShareView.vue
-[v] 기능 추가
-[] 기능 삭제
-[v] 버그 수정
feature/views/admin-home -> develop
- 관리자 페이지 홈 추가
- 회원 관리 페이지 추가
- 신고 내역 페이지 추가
- 인증 신청 내역 페이지 추가
- 공유 서비스 페이지 추가
- 택시 공유 서비스 페이지 추가
- 차량 공유 서비스 페이지 추가
- 결제 관리 페이지 추가
- 통계 페이지 연결
- Fix: 통계 컴포넌트들 axios에서 authAxios로 변경
- 라우터 연결 추가
- 관리자 페이지 출력 완료
- 라우터 연결 확인
- 통계 기능 정상 작동
> Feat: 관리자 페이지 추가

- hiapp/src/store/modules/websocket.js
-[] 기능 추가
-[] 기능 삭제
-[v] 버그 수정
bugfix/fix-websocket-link -> develop
- 웹소켓 연결 링크 수정
> Fix: 웹소켓 연결 링크 수정

- hiapp/src/components/commons/BottomNavComponent.vue
- hiapp/src/components/home/DetailInfoComponent.vue
- hiapp/src/components/home/TodayCarListComponent.vue
- hiapp/src/router/index.js
- hiapp/src/views/car-share/participant/CarShareHomeView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/car-share/reservation -> develop
- 오늘 차량 탑승 예정 내역 조회 페이지 구현
- 오늘 탑승 예정인 차량이 있다면 해당 리스트가 출력되고 없으면 없다는 문구 출력
- 탑승 예정인 항목 클릭하면 탑승 여부 선택하는 모달창 등장
> Feat: 과거 및 오늘 차량 예약 내역 조회 기능 추가

- hiapp/src/router/index.js
- hiapp/src/store/auth/auth.js
- hiapp/src/views/credit/CreditHistoryView.vue
- hiapp/src/views/credit/PurchaseCreditView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/credit -> develop
- 크레딧 충전 페이지 추가
- 크레딧 내역 조회 페이지 추가
> 크레딧 충전, 내역 조회 페이지 추가

- hiapp/package-lock.json
- hiapp/package.json
- hiapp/src/router/index.js
- hiapp/src/views/payment/PaymentFailView.vue
- hiapp/src/views/payment/PaymentSuccessView.vue
- hiapp/src/views/payment/PaymentView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/payment
- 결제 페이지, 결제 성공, 실패 페이지 추가
- 토스페이먼츠 결제 연동
> 토스페이먼츠 결제 관련 페이지 추가

- hiapp/src/components/taxi-share/TaxiShareJoinModal.vue
- hiapp/src/views/taxi-share/PathView.vue
-[] 기능 수정
feat/taxi-share -> develop
-택시 신청 모달 수정
> Modify: 택시 신청 모달 수정

- hiapp/src/store/auth/auth.js
- hiapp/src/views/payment/PaymentView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/payment -> develop
- 오타 수정
- 로그인 시 role 저장
> 오타 수정, 로그인 시 권한 저장

- hiapp/src/views/admin/AdminRegistrationView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/views/delete-registration -> develop
- 차량 등록 취소 시 등록 삭제 기능 추가
- 모달 연결
> Feat: 차량 등록 취소 시 등록 삭제 기능 추가

- hiapp/src/router/index.js
- hiapp/src/views/ChangePasswordView.vue
- hiapp/src/views/FindIdView.vue
- hiapp/src/views/LoginModalView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/auth -> develop
- 로그인 모달에서 이동할 수 있는 비밀번호 변경, 아이디 찾기 페이지 추가.
> 비밀번호 변경, 아이디 찾기 페이지 추가

- hiapp/src/components/car-share/CarSearchButton.vue
-[v] 기능 추가
-[] 기능 삭제
-[v] 버그 수정
bugfix/car-regi-btn -> develop
- 차량 등록 버튼 catch문 추가로 오류 해결
> Bugfix : 차량 등록 버튼 오류 수정

- hiapp/src/components/taxi-share/TaxiShareList.vue
- hiapp/src/views/taxi-share/PathView.vue
-[v] 기능 수정
feat/taxi-share -> develop
- css 수정
> Modify: css 수정

- hiapp/src/components/car-share/CarSearchButton.vue
- hiapp/src/components/car-share/MyCarShareSearchButton.vue
- hiapp/src/locales/en.json
- hiapp/src/locales/ko.json
- hiapp/src/views/MypageView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/views/i18n -> develop
- 마이페이지 국제화 적용
> Feat: 마이페이지 국제화 적용

- hiapp/src/components/taxi-share/TaxiShareJoinModal.vue
-[v] 기능 수정
feat/taxi-share -> develop
- 서버 엔드포인트 수정
> Modify: 서버 엔드포인트 수정

- hiapp/src/components/car-share/CarShareServiceRegiButton.vue
- hiapp/src/components/home/TodayCarListComponent.vue
- hiapp/src/components/home/TodayReservationListComponent.vue
- hiapp/src/components/home/TodayTaxiListComponent.vue
- hiapp/src/components/taxi-share/TaxiShareList.vue
- hiapp/src/locales/en.json
- hiapp/src/locales/ko.json
- hiapp/src/views/car-share/participant/CarShareHomeView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
chore/i18n/home -> develop
- 홈 화면  국제화 처리 완료
> Chore : 국제화 처리 및 디자인 추가 수정

- hiapp/src/components/car-share/CarRegiButton.vue
- hiapp/src/components/taxi-share/TaxiShareList.vue
- hiapp/src/locales/en.json
- hiapp/src/locales/ko.json
- hiapp/src/views/MypageView.vue
- hiapp/src/views/car-share/participant/CarShareHomeView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
chore/i18n/home -> develop
- 택시 차량 공유 리스트 부분 국제화 처리
> Chore : 국제화 처리 및 디자인 수정

- hiapp/src/App.vue
-[] 기능 추가
-[] 기능 삭제
-[] 버그 수정
-[v] 기타
chore/erase-annotation -> develop
- 웹소켓 연결 주석 제거
> Chore: 주석 제거

- hiapp/src/components/SignupStepOneComponent.vue
- hiapp/src/components/SignupStepTwoComponent.vue
- hiapp/src/components/home/TodayCarListComponent.vue
- hiapp/src/views/ChangePasswordView.vue
- hiapp/src/views/FindIdView.vue
- hiapp/src/views/LoginModalView.vue
- hiapp/src/views/SignupView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
feature/car-share/reservation -> develop
- 로그인 CSS 변경
- 이메일 찾기 CSS 변경
- 비밀번호 변경 CSS 변경
- 회원가입 CSS 변경
- 로그인 화면 소셜 로그인 버튼 삭제
- 이메일 찾기 및 비밀번호 변경 모바일 환경에 맞게 가로 길이 조정
- 회원가입 버튼 CSS 변경
> Modify: 회원 관련 CSS 수정

- hiapp/src/assets/style/CarRegistraion.css
- hiapp/src/assets/style/phone-main-view-common.css
- hiapp/src/components/car-share/CarEditForm.vue
- hiapp/src/components/car-share/CarRegiForm.vue
- hiapp/src/components/car-share/MyCarShareServiceListForm.vue
- hiapp/src/components/check-modal/AlertModal.vue
- hiapp/src/components/error-modal/ErrorModal.vue
- hiapp/src/components/modal/ConfirmModal.vue
- hiapp/src/locales/en.json
- hiapp/src/locales/ko.json
- hiapp/src/views/NotificationView.vue
- hiapp/src/views/car-share/CarRegistrationView.vue
- hiapp/src/views/car-share/CarShareServiceRegiFirstView.vue
- hiapp/src/views/car-share/CarShareServiceRegiSecondView.vue
- hiapp/src/views/car-share/MyCarSearchView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
design/carshare-part-and-notification -> dev
- 차량 crud 관련 모달창 디자인 수정
- 차량 서비스 crud 관련 모달창 및 디자인 수정
- 알림 디자인 수정
> Design : 차량 관련 디자인 변경 - 모달창 수정, 알림 디자인 수정

- hiapp/src/assets/style/CarRegistraion.css
- hiapp/src/assets/style/phone-main-view-common.css
- hiapp/src/components/car-share/CarEditForm.vue
- hiapp/src/components/car-share/CarRegiForm.vue
- hiapp/src/components/car-share/MyCarShareServiceListForm.vue
- hiapp/src/components/check-modal/AlertModal.vue
- hiapp/src/components/error-modal/ErrorModal.vue
- hiapp/src/components/modal/ConfirmModal.vue
- hiapp/src/locales/en.json
- hiapp/src/locales/ko.json
- hiapp/src/views/NotificationView.vue
- hiapp/src/views/car-share/CarRegistrationView.vue
- hiapp/src/views/car-share/CarShareServiceRegiFirstView.vue
- hiapp/src/views/car-share/CarShareServiceRegiSecondView.vue
- hiapp/src/views/car-share/MyCarSearchView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
design/modal -> dev
> Design : 모달창 디자인 수정

- hiapp/src/components/car-share/CarEditForm.vue
- hiapp/src/components/car-share/CarRegiButton.vue
- hiapp/src/components/car-share/CarRegiForm.vue
- hiapp/src/components/car-share/CarSearchButton.vue
- hiapp/src/components/car-share/CarServiceForm.vue
- hiapp/src/components/car-share/CarShareServiceRegiButton.vue
- hiapp/src/components/car-share/MyCarShareServiceListForm.vue
- hiapp/src/components/car-share/WriteAReviewButton.vue
- hiapp/src/components/car-share/participant/AllCarListComponent.vue
- hiapp/src/components/car-share/participant/CarInfoComponent.vue
- hiapp/src/components/car-share/participant/DriverInfoComponent.vue
- hiapp/src/components/car-share/participant/DrivingInfoComponent.vue
- hiapp/src/components/car-share/participant/PastCarListComponent.vue
- hiapp/src/components/commons/BottomNavComponent.vue
- hiapp/src/components/home/TodayCarListComponent.vue
- hiapp/src/components/statistics/MonthlyNewMemberComponent.vue
- hiapp/src/components/taxi-share/TaxiShareJoinModal.vue
- hiapp/src/components/taxi-share/TaxiShareList.vue
- hiapp/src/components/taxi-share/TaxiShareRegist.vue
- hiapp/src/main.js
- hiapp/src/views/admin/AdminHomeView.vue
- hiapp/src/views/admin/AdminMembersView.vue
- hiapp/src/views/car-share/CarShareServiceRegiSecondView.vue
- hiapp/src/views/car-share/participant/AvailableMapView.vue
- hiapp/src/views/car-share/participant/CarShareHomeView.vue
- hiapp/src/views/car-share/participant/CarshareDetailInformationView.vue
-[] 기능 추가
-[] 기능 삭제
-[] 버그 수정
core/axios-settings-> dev
> Core :  axios 재설정

- hiapp/src/components/CarShareInformationComponent.vue
- hiapp/src/components/car-share/CarEditForm.vue
- hiapp/src/components/car-share/CarRegiButton.vue
- hiapp/src/components/car-share/CarRegiForm.vue
- hiapp/src/components/car-share/CarSearchButton.vue
- hiapp/src/components/car-share/CarServiceForm.vue
- hiapp/src/components/car-share/CarShareServiceRegiButton.vue
- hiapp/src/components/car-share/MyCarShareServiceListForm.vue
- hiapp/src/components/car-share/WriteAReviewButton.vue
- hiapp/src/components/commons/BottomNavComponent.vue
- hiapp/src/components/commons/TopNavComponent.vue
- hiapp/src/components/home/TodayCarListComponent.vue
- hiapp/src/components/home/TodayTaxiListComponent.vue
- hiapp/src/main.js
- hiapp/src/store/auth/auth.js
- hiapp/src/views/car-share/participant/CarshareDetailInformationView.vue
-[v] 기능 추가
-[] 기능 삭제
-[] 버그 수정
chore/axios-> dev
- axios 설정
> Chore : 주소 경로 변경 AuthAxios
